info:
  contact: {}
  description: "\U0001F410 基于 gin + gorm 的轻量级工程项目"
  license: {}
  title: goat
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
