version: '3'
services:
  server:
    image: go-server:v1
    ports:
      - "32288:8888"
    volumes:
      #      - $PWD/conf:/app/conf # 方式一，挂载conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    # 方式二，使用environment
    environment:
      - SERVER_HTTPPORT=8888
      - SERVER_RUNMODE=release
      - LOG_LEVEL=info
